# Generated by Django 5.2.4 on 2025-07-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tattoo_name', models.CharField(max_length=50)),
                ('artist', models.CharField(blank=True, default='Unknown', help_text='The tattoo artist; leave blank for “Unknown”.', max_length=50, null=True)),
                ('image', models.ImageField(help_text='Upload an image of the tattoo.', upload_to='tattoos/')),
                ('style', models.CharField(blank=True, default='Unknown', help_text='Tattoo style, e.g. Gothic, Realism.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the tattoo in your currency.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this tattoo entry was created.')),
                ('added_by', models.ForeignKey(help_text='Which user/staff added this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tattoos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tattoo',
                'verbose_name_plural': 'Tattoos',
                'ordering': ['-created_at'],
            },
        ),
    ]
