# Generated by Django 5.2.1 on 2025-07-26 12:30

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2), accounts.validators.AppUserUsernameValidator(min_letters=2)]),
        ),
    ]
