# Generated by Django 5.2.1 on 2025-07-26 13:41

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[accounts.validators.BulgarianPhoneValidator()]),
        ),
    ]
